version: '2'
services:
  agentcentre-app:
    image: agentcentre
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://agentcentre-postgresql:5432/agentCentre
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://agentcentre-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://agentcentre-elasticsearch:9200
    ports:
      - 8080:8080
  agentcentre-postgresql:
    extends:
      file: postgresql.yml
      service: agentcentre-postgresql
  agentcentre-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: agentcentre-elasticsearch
